(()=>{
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const storageKey='dsa-forge-mastery-v2';
  const typeLabels={mcq:'MCQ',trace:'Trace / Output',complexity:'Complexity',design:'Data-structure choice',coding:'Coding / Algorithm',debug:'Debug / Reasoning'};
  const levelLabels={foundation:'Foundation',easy:'Easy',medium:'Medium',hard:'Hard'};
  const topicOrder=["Two Pointers","Sliding Window","Binary Search","Sorting & Intervals","Linked Lists","Stacks & Monotonic Structures","Hashing","Trees & BST","Heaps & Priority Queues","Tries & Strings","Backtracking","Greedy","1-D Dynamic Programming","2-D Dynamic Programming","Graphs","Advanced Graphs","Bit Manipulation","Math & Geometry","Advanced Data Structures","String Algorithms","Foundations & Complexity","Mixed Interview Patterns","Arrays & Strings","Greedy & Dynamic Programming","Mixed Patterns","Recursion & Backtracking","Sorting & Searching","Stacks & Queues"];
  const topics=topicOrder.filter(t=>QUESTION_BANK.some(q=>q.topic===t));
  const state=load(); let session=null; let codingSession=null;

  function fresh(){return {solved:{},attempts:{},stats:{attempted:0,correct:0,score:0},review:{},theme:'dark'}}
  function load(){try{return Object.assign(fresh(),JSON.parse(localStorage.getItem(storageKey)||'{}'))}catch{return fresh()}}
  function save(){localStorage.setItem(storageKey,JSON.stringify(state))}
  function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function applyTheme(){document.documentElement.dataset.theme=state.theme;$('#themeBtn').textContent=state.theme==='dark'?'☼':'☾'}
  function topicDescription(t){const m={"Foundations & Complexity":"Invariants, asymptotics, amortization and choosing the right abstraction.","Arrays & Strings":"Two pointers, sliding windows, prefix sums and array reasoning.","Linked Lists":"Pointer manipulation, cycles and structural invariants.","Stacks & Queues":"LIFO/FIFO, monotonic structures and window processing.","Hashing":"Membership, counting, deduplication and expected O(1) lookup.","Trees & BST":"Traversals, ordering, recursion and subtree reasoning.","Heaps & Priority Queues":"Priority access, top-k and bounded candidate sets.","Graphs":"Traversal, shortest paths, connectivity, DAGs and coloring.","Sorting & Searching":"Bounds, lower limits, selection, sweeps and intervals.","Recursion & Backtracking":"Recurrences, branching, pruning and state-space search.","Greedy & Dynamic Programming":"Optimal substructure, states, transitions and proofs.","Tries & Strings":"Prefix structures and autocomplete-oriented design.","Mixed Patterns":"Composite problems that force pattern selection and tradeoff reasoning."};return m[t]||'Curated problems designed to test understanding and transfer.'}

  // ----------------------------
  // Coding judge specification
  // ----------------------------
  const CODING_SPECS={
    'Two Sum: choose the right idea':{id:'two-sum',topic:'Arrays & Strings',pattern:'Hash lookup / complement',target:'O(n)',starter:`function solve(input) {\n  const { nums, target } = input;\n  // Return the two indices whose values add to target.\n  // Example: {nums:[2,7,11,15], target:9} -> [0,1]\n  \n}`,gen:n=>({nums:Array.from({length:n},(_,i)=>i*2+1),target:(n-1)*2+1+(n-2)*2+1}),tests:[
      [{nums:[2,7,11,15],target:9},[0,1]],[{nums:[3,2,4],target:6},[1,2]],[{nums:[3,3],target:6},[0,1]],[{nums:[1,5,9,12],target:14},[1,2]]
    ],hidden:[[{nums:[-3,4,8,1],target:5},[0,1]],[{nums:[10,-2,7,5],target:12},[1,3]],[{nums:[6,1,4,9,13],target:17},[2,3]],[{nums:[0,4,0,8],target:0},[0,2]]],cmp:(a,b)=>Array.isArray(a)&&Array.isArray(b)&&a.slice().sort((x,y)=>x-y).join(',')===b.slice().sort((x,y)=>x-y).join(','),hint:'For each value x, ask whether target-x has already appeared.'},
    'Maximum subarray':{id:'max-subarray',topic:'Arrays & Strings',pattern:"Kadane / local DP",target:'O(n)',starter:`function solve(nums) {\n  // Return the maximum possible sum of a non-empty contiguous subarray.\n  \n}`,gen:n=>Array.from({length:n},(_,i)=>(i%17)-8),tests:[[[ -2,1,-3,4,-1,2,1,-5,4],6],[[1],1],[[5,4,-1,7,8],23],[[ -2,-1],-1]],hidden:[[[3,-2,5,-1],6],[[ -5,-2,-8],-2],[[10,-1,-1,10],18],[[1,-3,4,-2,2,3,-8,4],7]],hint:'Track the best subarray that must end at the current position.'},
    'Longest substring without repeats':{id:'longest-substring',topic:'Sliding Window',pattern:'Sliding window + last seen',target:'O(n)',starter:`function solve(s) {\n  // Return length of longest substring with no repeated characters.\n  \n}`,gen:n=>Array.from({length:n},(_,i)=>String.fromCharCode(97+(i%26))).join(''),tests:[['abcabcbb',3],['bbbbb',1],['pwwkew',3],['',0]],hidden:[['dvdf',3],['anviaj',5],['abba',2],['tmmzuxt',5]],hint:'Maintain a valid window; when a duplicate appears, move the left boundary past its previous position.'},
    'Trapping Rain Water: choose the invariant':{id:'trap-water',topic:'Arrays & Strings',pattern:'Two boundaries / prefix maxima',target:'O(n)',starter:`function solve(height) {\n  // Return total trapped water.\n  \n}`,gen:n=>Array.from({length:n},(_,i)=>i%11===0?10:(i%7)),tests:[[[0,1,0,2,1,0,1,3,2,1,2,1],6],[[4,2,0,3,2,5],9],[[1,2,3],0],[[3,0,2,0,4],7]],hidden:[[[5,4,1,2],1],[[4,1,1,0,2,3],8],[[2,0,2],2],[[0,9,0,9,0],0]],hint:'At a position, trapped water is limited by the smaller of the best walls on its two sides.'},
    'Reverse a singly linked list':{id:'reverse-list',topic:'Linked Lists',pattern:'Pointer rewiring',target:'O(n)',starter:`function solve(values) {\n  // Treat values as a linked list; return the reversed value array.\n  \n}`,gen:n=>Array.from({length:n},(_,i)=>i),tests:[[[1,2,3,4,5],[5,4,3,2,1]],[[1],[1]],[[],[]],[[10,-2,7], [7,-2,10]]],hidden:[[[5,4,3],[3,4,5]],[[1,1,2,2],[2,2,1,1]],[[0,8,-1,6],[6,-1,8,0]]],hint:'Keep pointers for the reversed prefix and the unreversed suffix; save next before changing next.'},
    'Valid parentheses':{id:'valid-parentheses',topic:'Stacks & Queues',pattern:'Stack / nested scopes',target:'O(n)',starter:`function solve(s) {\n  // Return true if brackets are correctly matched.\n  \n}`,gen:n=>'()'.repeat(Math.ceil(n/2)).slice(0,n),tests:[['()',true],['()[]{}',true],['(]',false],['([{}])',true]],hidden:[['((()))',true],['([)]',false],['{[]}',true],['(((',false],['',true]],hint:'The most recently opened bracket must be the first one closed.'},
    'Sliding-window maximum':{id:'sliding-max',topic:'Stacks & Queues',pattern:'Monotonic deque',target:'O(n)',starter:`function solve(input) {\n  const { nums, k } = input;\n  // Return the maximum value of every size-k window.\n  \n}`,gen:n=>({nums:Array.from({length:n},(_,i)=>(i*17)%101),k:Math.max(2,Math.min(20,Math.floor(n/4)))}),tests:[[{nums:[1,3,-1,-3,5,3,6,7],k:3},[3,3,5,5,6,7]], [{nums:[1],k:1},[1]], [{nums:[9,7,5,3,1],k:2},[9,7,5,3]], [{nums:[4,2,12,3],k:2},[4,12,12]]],hidden:[[{nums:[1,5,2,3,7,1,9],k:3},[5,5,7,7,9]], [{nums:[8,8,8,1],k:2},[8,8,8]], [{nums:[-1,-2,-3,-4],k:2},[-1,-2,-3]]],hint:'The front should always be the best candidate; remove dominated values from the back.'},
    'First unique character':{id:'first-unique',topic:'Hashing',pattern:'Frequency map + scan',target:'O(n)',starter:`function solve(s) {\n  // Return the first character appearing exactly once, or ''.\n  \n}`,gen:n=>Array.from({length:n},(_,i)=>String.fromCharCode(97+(i%5))).join(''),tests:[['leetcode','l'],['loveleetcode','v'],['aabb',''],['z','z']],hidden:[['swiss','w'],['aabbcddee','c'],['aabbcc',''],['abcabcx','x']],hint:'You need frequency information and the original left-to-right order.'},
    'Longest consecutive sequence':{id:'longest-consecutive',topic:'Hashing',pattern:'Set + sequence starts',target:'O(n) expected',starter:`function solve(nums) {\n  // Return the length of the longest consecutive integer run.\n  \n}`,gen:n=>Array.from({length:n},(_,i)=>i*2),tests:[[[100,4,200,1,3,2],4],[[0,3,7,2,5,8,4,6,0,1],9],[ [1],1],[[],0]],hidden:[[[9,1,4,7,3,-1,0,5,8,-1,6],7],[[10,5,12,3,55,1,2,4],4],[[20,21,22,30,31],3]],hint:'Only start walking upward from x when x-1 is absent from the set.'},
    'Binary search boundary':{id:'lower-bound',topic:'Binary Search',pattern:'Lower bound',target:'O(log n)',starter:`function solve(input) {\n  const { nums, target } = input;\n  // Return the first index i with nums[i] >= target; or nums.length.\n  \n}`,gen:n=>({nums:Array.from({length:n},(_,i)=>i*2),target:Math.floor(n)}),tests:[[{nums:[1,2,4,4,5],target:4},2],[{nums:[1,2,4,4,5],target:3},2],[{nums:[1,2,4],target:9},3],[{nums:[],target:5},0]],hidden:[[{nums:[0,2,4,6,8],target:5},3],[{nums:[1,1,1,2,2,3],target:1},0],[{nums:[1,2,3],target:0},0]],hint:'Search for the first index where a monotone predicate becomes true.'},
    'Merge intervals':{id:'merge-intervals',topic:'Sorting & Intervals',pattern:'Sort + sweep',target:'O(n log n)',starter:`function solve(intervals) {\n  // Merge overlapping intervals and return sorted, non-overlapping intervals.\n  \n}`,gen:n=>Array.from({length:Math.max(2,Math.floor(n/5))},(_,i)=>[i*2,i*2+3]),tests:[[[[1,3],[2,6],[8,10],[15,18]],[[1,6],[8,10],[15,18]]],[[[1,4],[4,5]],[[1,5]]],[[[1,2]],[[1,2]]],[[[6,8],[1,9],[2,4],[4,7]],[[1,9]]]],hidden:[[[[1,5],[2,3]],[[1,5]]],[[[1,2],[3,4]],[[1,2],[3,4]]],[[[5,7],[1,3],[2,6]],[[1,7]]]],hint:'Sort by start; after sorting, only the current merged end matters.'},
    'Quickselect intuition':{id:'quickselect',topic:'Sorting & Searching',pattern:'Partition + selection',target:'O(n) average',starter:`function solve(input) {\n  const { nums, k } = input;\n  // Return the kth smallest value, where k is 1-based. Do not fully sort if you can avoid it.\n  \n}`,gen:n=>({nums:Array.from({length:n},(_,i)=>(i*37)%10000),k:Math.max(1,Math.floor(n/2))}),tests:[[{nums:[3,2,1,5,6,4],k:2},2],[{nums:[3,2,3,1,2,4,5,5,6],k:4},3],[{nums:[7],k:1},7]],hidden:[[{nums:[9,4,7,1,3,8,2],k:5},7],[{nums:[1,1,1,2,2,3],k:4},2]],hint:'After partition, only the side containing rank k needs further work.'},
    'Generate all subsets':{id:'subsets',topic:'Recursion & Backtracking',pattern:'Include / exclude recursion',target:'O(n·2^n)',starter:`function solve(nums) {\n  // Return every subset. Order of subsets does not matter.\n  \n}`,gen:n=>({dummy:Array.from({length:n},(_,i)=>i)}),tests:[[[1,2],[[],[1],[2],[1,2]]],[[0],[[],[0]]]],hidden:[[[1,2,3],[[],[1],[2],[3],[1,2],[1,3],[2,3],[1,2,3]]]],canon:(x)=>JSON.stringify(x.map(a=>a.slice().sort((a,b)=>a-b)).sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b)))),hint:'Each element creates exactly two choices: include or exclude.'},
    'Climbing stairs':{id:'climbing-stairs',topic:'Greedy & Dynamic Programming',pattern:'1-D DP',target:'O(n)',starter:`function solve(n) {\n  // You may climb 1 or 2 steps. Return number of ways to reach n.\n  \n}`,gen:n=>Math.min(25,n),tests:[[0,1],[1,1],[2,2],[5,8],[10,89]],hidden:[[3,3],[8,34],[15,987]],hint:'Partition solutions by the final move: 1 step or 2 steps.'},
    '0/1 Knapsack state':{id:'knapsack',topic:'Greedy & Dynamic Programming',pattern:'0/1 DP',target:'O(n·capacity)',starter:`function solve(input) {\n  const { weights, values, capacity } = input;\n  // Return the maximum total value using each item at most once.\n  \n}`,gen:n=>({weights:Array.from({length:n},(_,i)=>(i%7)+1),values:Array.from({length:n},(_,i)=>(i%13)+2),capacity:Math.floor(n*2)}),tests:[[{weights:[1,2,3],values:[6,10,12],capacity:5},22],[{weights:[1,3,4],values:[15,20,30],capacity:4},35],[{weights:[2,2,4,5],values:[3,4,8,8],capacity:6},12]],hidden:[[{weights:[2,3,4],values:[4,5,7],capacity:5},9],[{weights:[1,2,3,5],values:[5,6,8,9],capacity:7},19]],hint:'State: best value using a prefix of items under a capacity; each item is take-or-skip.'},
    'Longest increasing subsequence':{id:'lis',topic:'Greedy & Dynamic Programming',pattern:'DP / tails',target:'O(n log n)',starter:`function solve(nums) {\n  // Return length of the longest strictly increasing subsequence.\n  \n}`,gen:n=>Array.from({length:n},(_,i)=>(i*17)%100),tests:[[[10,9,2,5,3,7,101,18],4],[[0,1,0,3,2,3],4],[[7,7,7,7],1]],hidden:[[[3,10,2,1,20],3],[[2,2,2,2],1],[[1,3,6,7,9,4,10,5,6],6]],hint:'Track the best achievable tail for each increasing-subsequence length.'},
    'Edit distance transition':{id:'edit-distance',topic:'Greedy & Dynamic Programming',pattern:'2-D prefix DP',target:'O(mn)',starter:`function solve(input) {\n  const { a, b } = input;\n  // Return Levenshtein edit distance between a and b.\n  \n}`,gen:n=>({a:'abcdef'.repeat(Math.ceil(n/6)).slice(0,n),b:'abdfgh'.repeat(Math.ceil(n/6)).slice(0,n)}),tests:[[{a:'horse',b:'ros'},3],[{a:'intention',b:'execution'},5],[{a:'',b:'abc'},3],[{a:'abc',b:'abc'},0]],hidden:[[{a:'kitten',b:'sitting'},3],[{a:'flaw',b:'lawn'},2]],hint:'The last operation is delete, insert, or replace; define state on prefixes.'},
    'Count islands':{id:'count-islands',topic:'Graphs',pattern:'DFS/BFS components',target:'O(RC)',starter:`function solve(grid) {\n  // Return number of 4-directional islands of 1s.\n  // Do not mutate the caller's input if you can avoid it.\n  \n}`,gen:n=>Array.from({length:Math.max(4,Math.floor(Math.sqrt(n)))},(_,r)=>Array.from({length:Math.max(4,Math.floor(Math.sqrt(n)))},(_,c)=>(r+c)%3?1:0)),tests:[[[['1','1','0','0','0'],['1','1','0','0','0'],['0','0','1','0','0'],['0','0','0','1','1']],3],[[['1','0','1'],['0','1','0'],['1','0','1']],5],[[['0','0'],['0','0']],0]],hidden:[[[['1']],1],[[['1','1'],['1','0']],1],[[['1','0','0'],['1','0','1'],['0','1','1']],2]],hint:'Treat the grid as a graph: every traversal should mark one entire connected component.'}
  };

  function initCodingMeta(){
    return {passed:false, attempts:0, visiblePasses:0, hiddenPasses:0, complexityPasses:0, hintUsed:0, lastAttempt:0, nextReview:0, streak:0};
  }
  function codingSpecFor(q){return CODING_SPECS[q.title]||null}

  // ----------------------------
  // Dashboard / filters
  // ----------------------------
  function updateDashboard(){
    const solved=Object.keys(state.solved).length; const pct=Math.round(solved/QUESTION_BANK.length*100);
    $('#heroSolved').textContent=solved; $('#heroProgressBar').style.width=pct+'%'; $('#heroProgressText').textContent=`${pct}% of pool`;
    $('#topicCount').textContent=`${topics.length} topics · ${QUESTION_BANK.length} questions`;
    $('#topicGrid').innerHTML=topics.map(t=>{
      const qs=QUESTION_BANK.filter(q=>q.topic===t),done=qs.filter(q=>state.solved[q.id]?.status==='solved').length,p=Math.round(done/qs.length*100);
      const weak=topicWeakness(t); return `<button class="topic-card" data-topic="${esc(t)}" style="text-align:left;color:var(--text)"><div class="topic-top"><h3>${esc(t)}</h3><span class="muted">${done}/${qs.length}</span></div><p>${topicDescription(t)}</p><div class="topic-meter"><span style="width:${p}%"></span></div><div class="topic-foot"><span>${p}% complete</span><span>${weak<70&&attemptsForTopic(t).length>=3?'⚠ weak':'✓ tracked'}</span></div></button>`;
    }).join('');
    $$('.topic-card').forEach(b=>b.onclick=()=>{$('#topicFilter').value=b.dataset.topic;startQuiz()});
  }
  function populateFilters(){
    $('#topicFilter').innerHTML='<option value="all">All topics</option>'+topics.map(t=>`<option>${esc(t)}</option>`).join('');
    if(![...$('#levelFilter').options].some(o=>o.value==='unseen'))$('#levelFilter').insertAdjacentHTML('beforeend','<option value="unseen">Unseen only</option>');
  }
  function filteredQuestions(){
    const t=$('#topicFilter').value,l=$('#levelFilter').value,ty=$('#typeFilter').value;
    return QUESTION_BANK.filter(q=>(t==='all'||q.topic===t)&&(l==='all'||l==='unseen'||q.level===l)&&(ty==='all'||q.type===ty)&&(l!=='unseen'||!state.solved[q.id]));
  }
  function showOnly(id){['dashboardView','quizView','resultsView','codingView','reviewView','masteryView'].forEach(x=>document.getElementById(x)?.classList.add('hidden'));document.getElementById(id).classList.remove('hidden')}

  // ----------------------------
  // Quiz mode
  // ----------------------------
  function startQuiz(){const pool=filteredQuestions();if(!pool.length)return alert('No questions match those filters.');session={pool:[...pool].sort(()=>Math.random()-.5).slice(0,15),index:0,score:0,correct:0,current:null};showOnly('quizView');renderQuestion()}
  function renderQuestion(){
    const q=session.pool[session.index];session.current={selected:null,submitted:false,hints:0,usedHint:false};
    $('#quizCounter').textContent=`Question ${session.index+1} of ${session.pool.length}`;$('#quizScore').textContent=`Score ${session.score}`;$('#quizProgress').style.width=(session.index/session.pool.length*100)+'%';
    $('#qTopic').textContent=q.topic;$('#qLevel').textContent=levelLabels[q.level];$('#qType').textContent=typeLabels[q.type];$('#qTitle').textContent=q.title;$('#qBody').innerHTML=renderMarkdown(q.body);$('#qCode').classList.toggle('hidden',!q.code);if(q.code)$('#qCode').textContent=q.code;
    $('#hintBox').classList.add('hidden');$('#feedback').className='feedback hidden';$('#solutionBox').classList.add('hidden');$('#hintBtn').disabled=false;$('#hintBtn').textContent='Show hint 1';$('#submitBtn').disabled=false;$('#options').innerHTML='';$('#answerInput').value='';$('#answerInputWrap').classList.toggle('hidden',!['coding','debug'].includes(q.type));
    q.options.forEach((o,i)=>{const b=document.createElement('button');b.className='option';b.textContent=o;b.onclick=()=>{if(!session.current.submitted){session.current.selected=i;$$('.option').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')}};$('#options').appendChild(b)});
    renderSessionMap();$('#skillLens').textContent={complexity:'Ask what repeats and how often.',coding:'State the invariant or state before code.',design:'List required operations, then choose the structure.',trace:'Simulate only state affecting the next decision.',debug:'Find the violated invariant.',mcq:'Eliminate choices using definitions.'}[q.type]||'Think from constraints first.';
  }
  function renderSessionMap(){if(!session)return;$('#sessionMap').innerHTML=session.pool.map((q,i)=>`<div class="session-dot ${i===session.index?'current':state.solved[q.id]?.status==='solved'?'done':''}">${i+1}</div>`).join('')}
  function showHint(){const q=session.pool[session.index],n=session.current.hints;if(session.current.submitted)return;if(n>=q.hints.length){$('#hintBox').classList.remove('hidden');$('#hintBox').innerHTML='<strong>All hints shown.</strong>';return}session.current.hints++;session.current.usedHint=true;$('#hintBox').classList.remove('hidden');$('#hintBox').innerHTML=`<strong>Hint ${session.current.hints}</strong><p>${esc(q.hints[n])}</p>`;$('#hintBtn').textContent=session.current.hints<q.hints.length?`Show hint ${session.current.hints+1}`:'All hints shown'}
  function submit(){const q=session.pool[session.index];if(session.current.submitted)return;if(session.current.selected===null)return alert('Choose an answer first.');const correct=session.current.selected===q.answer;session.current.submitted=true;let earned=correct?(session.current.usedHint?.5:1):0;session.correct+=correct?1:0;session.score+=earned;state.stats.attempted++;state.stats.correct+=correct?1:0;state.stats.score+=earned;recordAttempt(q,correct,{hint:session.current.usedHint});$$('.option').forEach((b,i)=>{if(i===q.answer)b.classList.add('correct');if(i===session.current.selected&&i!==q.answer)b.classList.add('wrong')});$('#feedback').className=`feedback ${correct?'correct':'wrong'}`;$('#feedback').innerHTML=correct?`<strong>Correct.</strong> ${earned===1?'Clean first try.':'Correct after a hint.'}`:`<strong>Not quite.</strong> Review the explanation and retry later.`;showSolution(q);$('#submitBtn').disabled=true;$('#hintBtn').disabled=true;renderSessionMap();save();updateDashboard()}
  function showSolution(q){$('#solutionBox').classList.remove('hidden');$('#solutionContent').innerHTML=`<div class="solution-content"><h4>Explanation</h4>${renderMarkdown(q.solution)}<h4>What to remember</h4><ul>${q.teaching.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`}
  function nextQuestion(){if(!session.current.submitted){if(!confirm('Skip this question? It will be added to review.'))return;recordAttempt(session.pool[session.index],false,{skipped:true})}if(session.index<session.pool.length-1){session.index++;renderQuestion()}else finishQuiz()}
  function finishQuiz(){showOnly('resultsView');const total=session.pool.length,acc=Math.round(session.correct/total*100);$('#resultScore').textContent=session.score;$('#resultAccuracy').textContent=acc+'%';$('#resultCount').textContent=total;$('#resultsTitle').textContent=acc>=85?'Strong run.':acc>=65?'Solid progress.':'Useful diagnostic.';$('#resultsSubtitle').textContent=`${session.correct}/${total} correct. Weak areas are now queued for review.`;const by={};session.pool.forEach(q=>{by[q.topic]??={n:0,c:0};by[q.topic].n++;if(state.attempts[q.id]?.lastCorrect)by[q.topic].c++});$('#resultTopicList').innerHTML=Object.entries(by).map(([t,v])=>`<div class="result-topic-row"><strong>${esc(t)}</strong><div class="result-topic-bar"><span style="width:${Math.round(v.c/v.n*100)}%"></span></div><span class="muted">${v.c}/${v.n}</span></div>`).join('');updateDashboard()}

  function renderMarkdown(s){return String(s).split('\n\n').map(p=>`<p>${esc(p).replace(/`([^`]+)`/g,'<span class="inline-code">$1</span>')}</p>`).join('')}

  // ----------------------------
  // Coding lab
  // ----------------------------
  function codingProblems(){return QUESTION_BANK.filter(q=>q.type==='coding'&&codingSpecFor(q))}
  function startCoding(prefTopic='all'){const pool=codingProblems().filter(q=>prefTopic==='all'||q.topic===prefTopic);if(!pool.length)return alert('No executable coding problems are mapped to this topic yet.');codingSession={pool:pool.sort((a,b)=>(state.attempts[a.id]?.nextReview||0)-(state.attempts[b.id]?.nextReview||0)||Math.random()-.5),index:0};showOnly('codingView');renderCoding()}
  function renderCoding(){const q=codingSession.pool[codingSession.index],s=codingSpecFor(q),meta=state.attempts[q.id]||initCodingMeta();codingSession.q=q;codingSession.spec=s;codingSession.running=false;$('#codingCounter').textContent=`Coding ${codingSession.index+1}/${codingSession.pool.length}`;$('#codingProgress').style.width=(codingSession.index/codingSession.pool.length*100)+'%';$('#codingVerdict').textContent=meta.passed?'Passed before':'Not submitted';$('#codingTopic').textContent=q.topic;$('#codingLevel').textContent=levelLabels[q.level];$('#codingTitle').textContent=q.title;$('#codingPrompt').innerHTML=renderMarkdown(q.body);$('#codingConstraints').innerHTML=`<span>Target: ${esc(s.target)}</span><span>Pattern: ${esc(s.pattern)}</span><span>Hidden tests: ${s.hidden.length}</span>`;$('#codeEditor').value=s.starter;$('#testPanel').innerHTML='<div class="muted">Run visible tests to see exact inputs and outputs. Hidden tests remain locked until submission.</div>';$('#judgePanel').classList.add('hidden');$('#complexityResult').textContent='Run hidden tests to get an empirical estimate plus code-structure heuristic.';$('#codingPattern').textContent=s.pattern;$('#codingHint').textContent=s.hint;$('#codingWeakness').textContent=weakTopicText(q.topic);$('#codingGateTitle').textContent=masteryStatus(q.topic).label;$('#codingGateText').textContent=masteryStatus(q.topic).text}
  function runVisible(){judge(false)}
  async function judge(hidden){
    const q=codingSession.q,s=codingSession.spec,code=$('#codeEditor').value; const tests=hidden?s.hidden:s.tests;$('#codingVerdict').textContent='Running…';const results=[];
    for(let i=0;i<tests.length;i++){const [input,expected]=tests[i];results.push(await execute(code,input,expected,s.cmp,s.canon));if(!results.at(-1).ok)break}
    $('#testPanel').innerHTML=results.map((r,i)=>`<div class="test-row ${r.ok?'pass':'fail'}"><div><strong>Test ${i+1}</strong><span>${r.time.toFixed(1)} ms</span></div><pre>${esc(r.display)}</pre></div>`).join('');
    if(hidden){const passed=results.length===tests.length&&results.every(r=>r.ok);const complexity=passed?await estimateComplexity(code,s):null;recordCodingAttempt(q,passed,complexity);$('#codingVerdict').textContent=passed?'All hidden tests passed':'Hidden test failed';$('#judgePanel').classList.remove('hidden');$('#judgePanel').innerHTML=passed?'<strong>✓ Correctness gate passed.</strong><p>Your solution cleared every hidden test.</p>':'<strong>✕ Correctness gate failed.</strong><p>Use the failing case above. Hidden tests intentionally probe edge cases the visible set does not show.</p>';$('#complexityResult').innerHTML=complexity?complexity.html:'Complexity not assessed until correctness passes.';$('#codingGateTitle').textContent=masteryStatus(q.topic).label;$('#codingGateText').textContent=masteryStatus(q.topic).text;$('#codingWeakness').textContent=weakTopicText(q.topic);save();updateDashboard()}
    else $('#codingVerdict').textContent=results.every(r=>r.ok)?'Visible tests pass':'Visible failure';
  }
  function execute(code,input,expected,cmp,canon){return new Promise(resolve=>{const started=performance.now();let done=false;const workerCode=`self.onmessage=async e=>{try{${code}\n if(typeof solve!=='function')throw new Error('Define function solve(input).'); const out=await solve(e.data); self.postMessage({ok:true,out})}catch(err){self.postMessage({ok:false,error:String(err)})}}`;const blob=new Blob([workerCode],{type:'text/javascript'}),w=new Worker(URL.createObjectURL(blob));const timer=setTimeout(()=>{if(done)return;done=true;w.terminate();resolve({ok:false,time:performance.now()-started,display:'TIMEOUT — execution exceeded 1200 ms'})},1200);w.onmessage=e=>{if(done)return;done=true;clearTimeout(timer);w.terminate();let ok=false,display='';if(e.data.ok){try{ok=canon?canon(e.data.out)===canon(expected):cmp?cmp(e.data.out,expected):JSON.stringify(e.data.out)===JSON.stringify(expected);display=`input: ${JSON.stringify(input)}\nexpected: ${JSON.stringify(expected)}\nreceived: ${JSON.stringify(e.data.out)}`}catch(err){display=`Comparison error: ${err}`}}else display=`Runtime error: ${e.data.error}`;resolve({ok,time:performance.now()-started,display})};w.postMessage(input)})}
  async function estimateComplexity(code,s){let heuristic='';const loops=(code.match(/\b(for|while)\b/g)||[]).length;const nested=/for[\s\S]{0,500}(for|while)|while[\s\S]{0,500}(for|while)/.test(code);const rec=/function\s+solve[\s\S]*solve\s*\(/.test(code);if(nested)heuristic='Nested-loop signature suggests O(n²) or worse.';else if(rec&&/solve\(/.test(code))heuristic='Recursive calls detected; complexity depends on branching/state reuse.';else if(/sort\s*\(/.test(code))heuristic='Built-in sort suggests at least O(n log n) comparison-style work.';else if(loops===1)heuristic='Single-loop signature is compatible with linear work.';else heuristic='No strong static signal; empirical timing was used.';
    const sizes=[100,250,600];const times=[];if(s.gen){for(const n of sizes){const input=s.gen(n);const t0=performance.now();await runOnly(code,input);times.push(Math.max(.05,performance.now()-t0))}}let empirical='';if(times.length===3){const slope=Math.log(times[2]/times[0])/Math.log(sizes[2]/sizes[0]);empirical=`Observed scaling exponent ≈ ${slope.toFixed(2)} (rough browser estimate).`;}const targetGood=targetMatches(s.target,heuristic,empirical);return {ok:targetGood,html:`<strong>${targetGood?'✓':'△'} Expected: ${esc(s.target)}</strong><p>${esc(heuristic)} ${esc(empirical)}</p><small>Complexity feedback is advisory and browser-timing based; use reasoning about the algorithm as the final proof.</small>`}}
  function runOnly(code,input){return new Promise(resolve=>{const t=performance.now();let done=false;const w=new Worker(URL.createObjectURL(new Blob([`self.onmessage=async e=>{try{${code}; if(typeof solve!=='function')throw Error('solve missing'); await solve(e.data); self.postMessage(1)}catch{self.postMessage(0)}}`],{type:'text/javascript'})));const tm=setTimeout(()=>{if(!done){done=true;w.terminate();resolve(1200)}} ,1200);w.onmessage=()=>{if(done)return;done=true;clearTimeout(tm);w.terminate();resolve(performance.now()-t)};w.postMessage(input)})}
  function targetMatches(target,h,e){if(target.includes('log n'))return /sort|binary|heap|log/i.test(h+e);if(target.includes('n²'))return /O\(n²\)/.test(h);if(target.includes('2^n'))return /Recursive/.test(h)||/exponent/i.test(e);return /single-loop|linear|O\(n\)/i.test(h+e)||!nestedHeuristic(h)}
  function nestedHeuristic(h){return /Nested-loop/.test(h)}
  function resetCode(){if(codingSession)$('#codeEditor').value=codingSession.spec.starter}
  function recordCodingAttempt(q,pass,complexity){const now=Date.now(),old=state.attempts[q.id]||initCodingMeta();old.attempts++;old.lastAttempt=now;old.hiddenPasses+=pass?1:0;old.complexityPasses+=complexity?.ok?1:0;old.passed=pass;old.lastCorrect=pass;old.hintUsed=0;old.streak=pass?old.streak+1:0;const intervals=[86400000,3*86400000,7*86400000,14*86400000];old.nextReview=now+intervals[Math.min(old.streak,intervals.length-1)];state.attempts[q.id]=old;state.solved[q.id]={status:pass?'solved':'review',last:now};state.review[q.id]=old.nextReview}
  function recordAttempt(q,correct,extra={}){const now=Date.now(),old=state.attempts[q.id]||initCodingMeta();old.attempts++;old.lastAttempt=now;old.lastCorrect=correct;old.streak=correct?old.streak+1:0;old.nextReview=now+(correct?(old.streak>=3?7:old.streak>=2?3:1):0.25)*86400000;state.attempts[q.id]=old;state.review[q.id]=old.nextReview;state.solved[q.id]={status:correct?'solved':'review',last:now,hints:extra.hint?1:0}}

  // ----------------------------
  // Review + mastery
  // ----------------------------
  function dueQuestions(){const now=Date.now();return QUESTION_BANK.filter(q=>state.review[q.id]&&state.review[q.id]<=now).sort((a,b)=>(state.review[a.id]||0)-(state.review[b.id]||0))}
  function attemptsForTopic(t){return QUESTION_BANK.filter(q=>q.topic===t&&state.attempts[q.id]).map(q=>state.attempts[q.id])}
  function topicWeakness(t){const arr=attemptsForTopic(t);if(!arr.length)return 100;return Math.round(100*arr.filter(a=>a.lastCorrect).length/arr.length)}
  function weakTopicText(t){const a=attemptsForTopic(t);if(a.length<3)return 'Not enough evidence yet. Keep practicing.';const p=topicWeakness(t);return p<70?`Weak signal: ${p}% recent attempt accuracy. Review due items before adding harder problems.`:`Current signal: ${p}% recent attempt accuracy.`}
  function masteryStatus(t){const qs=QUESTION_BANK.filter(q=>q.topic===t);const arr=qs.map(q=>state.attempts[q.id]).filter(Boolean);const acc=arr.length?arr.filter(a=>a.lastCorrect).length/arr.length:0;const coding=qs.filter(q=>q.type==='coding'&&state.attempts[q.id]?.hiddenPasses).length;const complexity=qs.filter(q=>q.type==='coding'&&state.attempts[q.id]?.complexityPasses).length;if(arr.length>=5&&acc>=.8&&coding>=2&&complexity>=1)return {label:'MASTERED',text:'Evidence gate passed: consistent accuracy + coding + complexity evidence.'};if(arr.length>=3)return {label:'BUILDING',text:`Need ~${Math.max(0,5-arr.length)} more attempts, ≥80% accuracy, 2 coding passes and 1 complexity pass to unlock mastery.`};return {label:'LOCKED',text:'Build at least 3 attempts before this topic can be assessed for mastery.'}}
  function renderReview(){const due=dueQuestions();const weak=[...topics].map(t=>[t,topicWeakness(t)]).filter(x=>x[1]<70&&attemptsForTopic(x[0]).length>=3).sort((a,b)=>a[1]-b[1]);$('#reviewStats').innerHTML=`<div class="review-stat"><strong>${due.length}</strong><span>due now</span></div><div class="review-stat"><strong>${weak.length}</strong><span>weak topics</span></div><div class="review-stat"><strong>${Object.keys(state.solved).length}</strong><span>completed</span></div>`;const items=[...due.slice(0,20)];$('#reviewList').innerHTML=items.length?items.map(q=>`<button class="review-row" data-id="${q.id}"><div><strong>${esc(q.title)}</strong><span>${esc(q.topic)} · ${levelLabels[q.level]}</span></div><em>${reviewLabel(q.id)}</em></button>`).join(''):`<div class="results-card"><h3>Review queue is clear.</h3><p class="muted">Keep solving. When evidence says an older concept needs reinforcement, it will appear here automatically.</p></div>`;$$('.review-row').forEach(b=>b.onclick=()=>{const q=QUESTION_BANK.find(x=>x.id===b.dataset.id);if(q.type==='coding'&&codingSpecFor(q)){showOnly('codingView');codingSession={pool:[q],index:0};renderCoding()}else{$('#topicFilter').value=q.topic;startQuiz()}})}
  function reviewLabel(id){const d=state.review[id],days=Math.max(0,Math.ceil((d-Date.now())/86400000));return d<=Date.now()?'Due now':`Due in ${days}d`}
  function renderMastery(){const html=topics.map(t=>{const arr=attemptsForTopic(t),p=topicWeakness(t),s=masteryStatus(t);const coding=QUESTION_BANK.filter(q=>q.topic===t&&q.type==='coding').filter(q=>state.attempts[q.id]?.hiddenPasses).length;return `<div class="mastery-row"><div><span class="eyebrow">${esc(t)}</span><h3>${s.label}</h3><p>${esc(s.text)}</p></div><div class="mastery-meter"><div><span style="width:${Math.min(100,p)}%"></span></div><small>${p}% accuracy · ${coding} coding passes · ${arr.length} attempts</small></div></div>`}).join('');$('#masteryList').innerHTML=html}

  function dashboard(){showOnly('dashboardView');updateDashboard()}
  function renderDashboardExtras(){const codingMode=$('#codingModeBtn');codingMode.onclick=()=>startCoding($('#topicFilter').value);$('#reviewModeBtn').onclick=()=>{showOnly('reviewView');renderReview()};$('#masteryModeBtn').onclick=()=>{showOnly('masteryView');renderMastery()};$('#reviewBackBtn').onclick=dashboard;$('#masteryBackBtn').onclick=dashboard;$('#codingBackBtn').onclick=dashboard;$('#codingNextBtn').onclick=()=>{if(codingSession&&codingSession.index<codingSession.pool.length-1){codingSession.index++;renderCoding()}else dashboard()};$('#runVisibleBtn').onclick=runVisible;$('#submitHiddenBtn').onclick=()=>judge(true);$('#resetCodeBtn').onclick=resetCode}

  $('#themeBtn').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';save();applyTheme()};
  $('#resetBtn').onclick=()=>{if(confirm('Reset all Forge progress, review history and mastery evidence?')){localStorage.removeItem(storageKey);location.reload()}};
  $('#startBtn').onclick=startQuiz;$('#hintBtn').onclick=showHint;$('#submitBtn').onclick=submit;$('#skipBtn').onclick=nextQuestion;$('#backBtn').onclick=dashboard;$('#resultDashBtn').onclick=dashboard;$('#retryBtn').onclick=()=>{session.index=0;session.score=0;session.correct=0;session.pool=[...filteredQuestions()].sort(()=>Math.random()-.5).slice(0,15);showOnly('quizView');renderQuestion()};$('#copySolutionBtn').onclick=async()=>{await navigator.clipboard?.writeText($('#solutionContent').innerText||'');$('#copySolutionBtn').textContent='✓';setTimeout(()=>$('#copySolutionBtn').textContent='⧉',900)};
  $$('.mode-card').forEach(b=>b.onclick=()=>{$('#levelFilter').value=b.dataset.level;$('#topicFilter').value='all';startQuiz()});$('#topicFilter').onchange=()=>{};populateFilters();renderDashboardExtras();applyTheme();updateDashboard();
})();
